twig:
    file_name_pattern: '*.twig'
    form_themes:
        - theme/form_theme.html.twig
    paths:
        '%kernel.project_dir%/assets/images': images


when@test:
    twig:
        strict_variables: true
